on: [push]

jobs:
  ClangFormatCheck:
    runs-on: ubuntu-latest
    name: check clang format
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check clang format
      run: ./.github/automation/clang-format.sh
      shell: bash
  CI_test_job:
    runs-on: ubuntu-latest
    name: Test for oneDNN
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test action step
      uses: ./.github/actions/test_action